# Generated by Django 3.2.12 on 2022-04-09 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='2022 NCAA Bracket', max_length=100)),
                ('slug', models.SlugField(default='2022-ncaa-bracket', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='march_api.bracket')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=40)),
                ('mascot', models.CharField(max_length=40)),
                ('seed', models.IntegerField(default=0)),
                ('region_position', models.IntegerField()),
                ('ppg', models.FloatField()),
                ('asm', models.FloatField()),
                ('rpg', models.FloatField()),
                ('oppg', models.FloatField()),
                ('fgp', models.FloatField()),
                ('ofgp', models.FloatField()),
                ('ftp', models.FloatField()),
                ('oftp', models.FloatField(default=None)),
                ('thpp', models.FloatField()),
                ('othpp', models.FloatField()),
                ('twpp', models.FloatField()),
                ('otwpp', models.FloatField()),
                ('shooteff', models.FloatField()),
                ('oshooteff', models.FloatField()),
                ('fgmpg', models.FloatField()),
                ('ofgmpg', models.FloatField()),
                ('fgapg', models.FloatField()),
                ('ofgapg', models.FloatField()),
                ('thpmpg', models.FloatField()),
                ('thpapg', models.FloatField()),
                ('ftmpg', models.FloatField()),
                ('ftapg', models.FloatField()),
                ('orpg', models.FloatField()),
                ('drpg', models.FloatField()),
                ('bpg', models.FloatField()),
                ('obpg', models.FloatField()),
                ('spg', models.FloatField()),
                ('ospg', models.FloatField()),
                ('topg', models.FloatField()),
                ('otopg', models.FloatField()),
                ('pfpg', models.FloatField()),
                ('opfpg', models.FloatField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='march_api.region')),
            ],
            options={
                'ordering': ['region_position'],
            },
        ),
    ]
