# Generated by Django 3.2.12 on 2022-04-10 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='2022 NCAA Bracket', max_length=100)),
                ('slug', models.SlugField(default='2022-ncaa-bracket', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='march_api.bracket')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=40)),
                ('mascot', models.CharField(max_length=40)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('region_position', models.IntegerField(blank=True, null=True)),
                ('ppg', models.FloatField()),
                ('opp_ppg', models.FloatField()),
                ('avg_score_margin', models.FloatField()),
                ('reb_pg', models.FloatField()),
                ('opp_reb_pg', models.FloatField()),
                ('fgp', models.FloatField()),
                ('opp_fgp', models.FloatField()),
                ('ftp', models.FloatField()),
                ('opp_ftp', models.FloatField()),
                ('thpp', models.FloatField()),
                ('opp_thpp', models.FloatField()),
                ('twpp', models.FloatField()),
                ('opp_twpp', models.FloatField()),
                ('shoot_eff', models.FloatField()),
                ('opp_shoot_eff', models.FloatField()),
                ('fgmpg', models.FloatField()),
                ('opp_fgmpg', models.FloatField()),
                ('fgapg', models.FloatField()),
                ('opp_fgapg', models.FloatField()),
                ('thpmpg', models.FloatField()),
                ('thpapg', models.FloatField()),
                ('opp_thpmpg', models.FloatField()),
                ('opp_thpapg', models.FloatField()),
                ('ftmpg', models.FloatField()),
                ('ftapg', models.FloatField()),
                ('opp_ftmpg', models.FloatField()),
                ('opp_ftapg', models.FloatField()),
                ('off_rpg', models.FloatField()),
                ('def_rpg', models.FloatField()),
                ('opp_off_rpg', models.FloatField()),
                ('opp_def_rpg', models.FloatField()),
                ('bpg', models.FloatField()),
                ('opp_bpg', models.FloatField()),
                ('spg', models.FloatField()),
                ('opp_spg', models.FloatField()),
                ('topg', models.FloatField()),
                ('opp_topg', models.FloatField()),
                ('pfpg', models.FloatField()),
                ('opp_pfpg', models.FloatField()),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='march_api.region')),
            ],
            options={
                'ordering': ['region_position'],
            },
        ),
    ]
