# Generated by Django 3.2.12 on 2022-04-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('march_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='oftp',
            field=models.FloatField(default=None),
        ),
    ]
