# Generated by Django 3.2.12 on 2022-04-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('march_api', '0003_auto_20220417_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='college',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
