# Generated by Django 3.2.12 on 2022-04-18 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('march_api', '0004_alter_team_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='march_api.team'),
        ),
    ]
