# Generated by Django 3.2.12 on 2022-04-18 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('march_api', '0005_alter_stat_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='march_api.team'),
        ),
    ]
