# Generated by Django 3.2.12 on 2022-04-20 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('march_api', '0007_auto_20220419_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='bracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='march_api.bracket'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='march_api.region'),
        ),
    ]
