# Generated by Django 3.2.12 on 2022-04-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('march_api', '0008_auto_20220420_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='region_position',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
